language: python

# Use new travis-ci infrastructure
sudo: false


# Most of this is from http://conda.pydata.org/docs/travis.html
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda install -y --file requirements.txt --channel bioconda --channel conda-forge

script:
    - snakemake --configfile=config/test-config.yaml
