# urls for reference genomes from Ensembl and from UCSC

references:

  fly:

    ensembl_BDGP6_to_ucsc_dm6:
      fastas:
        ensembl:
          url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.23_FB2018_04/fasta/dmel-all-chromosome-r6.23.fasta.gz'
          filterin: None
          filterout: None
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz'
          filterin: None
          filterout: None
      args:
          from: 'ensembl'
          to: 'ucsc'

  chicken:

    ensembl_Gallus_gallus-5.0_to_ucsc_galGal5:
      fastas:
        ensembl:
          url: 'ftp://ftp.ensembl.org/pub/release-94/fasta/gallus_gallus/dna/Gallus_gallus.Gallus_gallus-5.0.dna_sm.toplevel.fa.gz'
          filterin: None
          filterout: None
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/galGal5/bigZips/galGal5.fa.gz'
          filterin: None
          filterout: None
      args:
          from: 'ensembl'
          to: 'ucsc'

  human:

    ensembl_GRCh38.p12_to_ucsc_hg38:
      fastas:
        ensembl:
          url: 'ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.toplevel.fa.gz'
          filterin: None
          filterout: 'REF'
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chromFa.tar.gz'
          filterin: None
          filterout: '_alt'
      args:
          from: 'ensembl'
          to: 'ucsc'

  mouse:

    ensembl_GRCm38.p6_to_ucsc_mm10:
      fastas:
        ensembl:
          url: 'ftp://ftp.ensembl.org/pub/release-94/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz'
          filterin: None
          filterout: None
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/chromFa.tar.gz'
          filterin: None
          filterout: None
      args:
          from: 'ensembl'
          to: 'ucsc'

  zebrafish:

    ensembl_GRCz11_to_ucsc_danRer11:
      fastas:
        ensembl:
          url: 'ftp://ftp.ensembl.org/pub/release-94/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa.gz'
          filterin: None
          filterout: None
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/danRer11/bigZips/danRer11.fa.gz'
          filterin: None
          filterout: '_alt'
      args:
          from: 'ensembl'
          to: 'ucsc'

  rat:

    ensembl_Rnor_6.0_to_ucsc_rn6:
      fastas:
        ensembl:
          url: 'ftp://ftp.ensembl.org/pub/release-94/fasta/rattus_norvegicus/dna/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz'
          filterin: None
          filterout: None
        ucsc:
          url: 'ftp://hgdownload.soe.ucsc.edu/goldenPath/rn6/bigZips/rn6.fa.gz'
          filterin: None
          filterout: None
      args:
          from: 'ensembl'
          to: 'ucsc'
