# urls for reference genomes from Ensembl and from UCSC

references:

  test:

    fasta1_to_fasta2:
      - fasta1: 'test-data/fasta1.fa.gz'
      - fasta2: 'test-data/fasta2.tar.gz'
      - args:
          #format: None    or    ['mitochondrion_genome', 'rDNA']
          filterout: None
          filterin: None

    fasta1-broken_to_fasta2:
      - fasta1-broken: 'test-data/fasta1-broken.fa.gz'
      - fasta2: 'test-data/fasta2.tar.gz'
      - args:
          #format: None    or    ['mitochondrion_genome', 'rDNA']
          filterout: ['1', '2']
          filterin: None

    fasta1_to_fasta2-filtered:
      - fasta1: 'test-data/fasta1.fa.gz'
      - fasta2: 'test-data/fasta2.tar.gz'
      - args:
          #format: None    or    ['mitochondrion_genome', 'rDNA']
          filterout: ['mitochondrion_genome']
          filterin: ['1', '2']
