name: tests
on: push
jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: build env
      run: |
          eval "$(conda shell.bash hook)"
          conda env create -y -p ./env \
            --file requirements.yaml

    - name: run workflow
      run: |
          eval "$(conda shell.bash hook)"
          conda activate ./env
          set -e
          time snakemake -pr -j4 --configfile config/test-config.yaml --resources wget_limit=2

    - name: run pytest
      run: |
          eval "$(conda shell.bash hook)"
          conda activate ./env
          pytest
