name: tests
on: push
jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: build env
      run: |
          eval "$(conda shell.bash hook)"
          conda env create -y -p ./env \
            --file requirements.yaml

    - name: run workflow
      run: |
          eval "$(conda shell.bash hook)"
          conda activate ./env
          set -e
          time snakemake -pr -j4 --configfile config/test-config.yaml --resources wget_limit=2
          diff mappings/test/fasta1_to_fasta2/mappings_fasta1_to_fasta2.tsv tests/expected_results/fasta1_to_fasta2/mappings_fasta1_to_fasta2.tsv \
            > tests/expected_results/diff.log 2>> tests/expected_results/diff.log
          if [ -s tests/expected_results/diff.log ]
          then
            echo "FAILED, see tests/expected_results/diff.log"
            exit 1
          else
            echo "PASSED"
          fi

    - name: run pytest
      run: |
          eval "$(conda shell.bash hook)"
          conda activate ./env
          pytest
